services:
  halo:
    container_name: halo-nginx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_PROXY_SERVER: ${HALO_PROXY_SERVER_URL:-http://localhost:8090}
    ports:
      - "8089:80"
    restart: unless-stopped
    networks:
      - halo

  proxy-server:
    image: ghcr.io/danvergara/jumble-proxy-server:latest
    environment:
      - ALLOW_ORIGIN=${HALO_SOCIAL_URL:-http://localhost:8089}
      - HALO_PROXY_GITHUB_TOKEN=${HALO_PROXY_GITHUB_TOKEN}
      - ENABLE_PPROF=true
      - PORT=8080
    ports:
      - "8090:8080"
    networks:
      - halo

  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    container_name: halo-nostr-relay
    ports:
      - "7000:8080"
    environment:
      - RUST_LOG=warn,nostr_rs_relay=info
    volumes:
      - relay-data:/usr/src/app/db
    networks:
      - halo
    restart: unless-stopped

volumes:
  relay-data:

networks:
  halo:
